/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_acm_keyboard_win_KeyboardHook_PollThread */

#ifndef _Included_com_acm_keyboard_win_KeyboardHook_PollThread
#define _Included_com_acm_keyboard_win_KeyboardHook_PollThread
#ifdef __cplusplus
extern "C" {
#endif
#undef com_acm_keyboard_win_KeyboardHook_PollThread_MIN_PRIORITY
#define com_acm_keyboard_win_KeyboardHook_PollThread_MIN_PRIORITY 1L
#undef com_acm_keyboard_win_KeyboardHook_PollThread_NORM_PRIORITY
#define com_acm_keyboard_win_KeyboardHook_PollThread_NORM_PRIORITY 5L
#undef com_acm_keyboard_win_KeyboardHook_PollThread_MAX_PRIORITY
#define com_acm_keyboard_win_KeyboardHook_PollThread_MAX_PRIORITY 10L
/*
 * Class:     com_acm_keyboard_win_KeyboardHook_PollThread
 * Method:    checkKeyboardChanges
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_acm_keyboard_win_KeyboardHook_00024PollThread_checkKeyboardChanges
  (JNIEnv *, jobject);

/*
 * Class:     com_acm_keyboard_win_KeyboardHook_PollThread
 * Method:    cleanup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_acm_keyboard_win_KeyboardHook_00024PollThread_cleanup
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
